apiVersion: v1
kind: Service
metadata:
  name: misskey
	annotations:
		dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
  selector:
    app: misskey
